version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '8090:8090'
  db:
    image: postgres:17-alpine
    container_name: bootcamp_postgres_17
    restart: always
    environment:
      POSTGRES_DB: bootcamp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/password_db
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    secrets:
      - password_db

secrets:
  password_db:
    file: password_db