# Use an official Maven image as the base image
FROM maven:3.8.5-openjdk-17-slim AS build
# Set the working directory in the container
WORKDIR /app
# Copy the parent pom.xml
COPY pom.xml .
# Install the parent tusing Maven
RUN mvn install -N
# Copy the pom.xml and the project files to the container
COPY h23ApiGateway/pom.xml /app/h23ApiGateway/
COPY h23ApiGateway/src /app/h23ApiGateway/src
# Set the working directory in the container
WORKDIR /app/h23ApiGateway
# Build the application using Maven
RUN mvn clean package -DskipTests

# Use an official OpenJDK image as the base image
FROM openjdk:17-jdk-slim
# Set the working directory in the container
WORKDIR /app
# Copy the built JAR file from the previous stage to the container
COPY --from=build /app/h23ApiGateway/target/api-gateway-executable.jar app.jar
# Set the command to run the application
CMD ["java", "-jar", "app.jar"]
