apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2025-07-13T20:38:42Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: steve
      operation: Update
      time: '2025-07-13T21:26:15Z'
  name: playlist-server-service
  namespace: default
  resourceVersion: '35058'
  uid: 551fecd4-ca09-4b9e-91c2-935dc5d6b345
spec:
  clusterIP: 10.43.26.69
  clusterIPs:
    - 10.43.26.69
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8090
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-playlist-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
