apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/playlist-client"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2025-07-13T22:21:54Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8091,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: steve
      operation: Update
      time: '2025-07-13T22:21:54Z'
  name: playlist-client
  namespace: default
  resourceVersion: '36404'
  uid: ae1cd456-7aef-480e-a269-7ca82186eac4
spec:
  clusterIP: 10.43.85.90
  clusterIPs:
    - 10.43.85.90
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-playlist-client
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
