apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2025-07-13T14:13:26Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":5672,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":15672,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: steve
      operation: Update
      time: '2025-07-13T15:09:05Z'
  name: rabbitmq-service
  namespace: default
  resourceVersion: '26647'
  uid: 7013423a-16b3-4052-916d-36486156afa6
spec:
  clusterIP: 10.43.203.72
  clusterIPs:
    - 10.43.203.72
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: management
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
