spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: server_route
              uri: lb://PlaylistService
              predicates:
                - Path=/server/**
              filters:
                - StripPrefix=1
            - id: client_route
              uri: lb://PlaylistClientService
              predicates:
                - Path=/client/**
              filters:
                - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8500/realms/example/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8500/realms/example
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: H9GDW6PWfwYJpcurEK8SXkcK5Bt8ukmy
            authorization-grant-type: authorization_code
            scope: openid
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

server:
  port: 8080

management:
  endpoints.web.exposure.include: 'gateway, prometheus, metrics, info, health, env'
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1
