spring:
  config:
    import: classpath:secrets.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/bootcamp
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:create_playlist_schema.sql
      data-locations: classpath:prepare_playlist_data.sql
      mode: always
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: playlist
        format_sql: true
    open-in-view: false
server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.colvir.bootcamp.homework5
