app:
  name: bootcamp_web_server
spring:
  application:
    name: PlaylistService
  config:
    import: classpath:secrets.yaml, optional:configserver:http://localhost:8600
  datasource:
    url: jdbc:postgresql://localhost:5433/bootcamp?currentSchema=playlist
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db-migration/changelog.xml
    default-schema: playlist
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: playlist
        format_sql: true
    open-in-view: false
  cache:
    type: hazelcast
  hazelcast:
    config: classpath:hazelcast-client.yaml
management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh, beans, mappings'
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.colvir.bootcamp.homework5

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/