app:
  name: bootcamp_web_client
spring:
  config:
    import: classpath:secrets.yaml, optional:configserver:http://localhost:8600
  application:
    name: PlaylistClientService
server:
  port: 8091
management:
  endpoints.web.exposure.include: 'prometheus, metrics, info, health, env, refresh, beans, mappings'
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      access: read_only
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
